version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5

  - package-ecosystem: npm
    directory: /terraform/lambda
    schedule:
      interval: weekly
    groups:
      aws-sdk:
        patterns:
          - "@aws-sdk/*"

  - package-ecosystem: terraform
    directory: /terraform
    schedule:
      interval: weekly

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
